### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by Marrin** [python-forum-de/python-forum-de.github.io#1]
Replacing the default about page with content.

**Comment by Kebap** [comment]
Link zum Wiki eingefügt, siehe https://github.com/python-forum-de/python-forum-de.github.io/pull/3

Dort gibt es genug "About" Infos. Macht keinen Sinn, sie an mehreren Stellen zu pflegen.

Die Infos über Jekyll sind erstmal drin geblieben, falls sie noch jemand benötigen sollte, allerdings entsprechend tituliert.

Leider ist die Seite dadurch zweisprachig, deutsch und englisch gemischt.,
